//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the StronglyTypedId source generator
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591 // publicly visible type or member must be documented

#nullable enable

namespace StronglyTypedIds
{
    /// <summary>
    /// Used to control the default strongly typed ID values. Apply to an assembly using
    /// <code>[assembly:StronglyTypedIdDefaults(Template.Int)]</code> for example
    /// </summary>
    [global::System.AttributeUsage(global::System.AttributeTargets.Assembly, Inherited = false, AllowMultiple = false)]
    [global::System.Diagnostics.Conditional("STRONGLY_TYPED_ID_USAGES")]
    public sealed class StronglyTypedIdDefaultsAttribute : global::System.Attribute
    {
        /// <summary>
        /// Set the default template to use for strongly typed IDs
        /// </summary>
        /// <param name="template">The built-in template to use to generate the ID.</param>
        /// <param name="templateNames">The names of additional custom templates to use to generate the ID.
        /// Templates must be added to the project using the format NAME.typedid,
        /// where NAME is the name of the template passed in <paramref name="templateNames"/>.
        /// </param>
        public StronglyTypedIdDefaultsAttribute(global::StronglyTypedIds.Template template, params string[] templateNames)
        {
        }

        /// <summary>
        /// Set the default template to use for strongly typed IDs
        /// </summary>
        /// <param name="templateName">The name of the template to use to generate the ID.
        /// Templates must be added to the project using the format NAME.typedid,
        /// where NAME is the name of the template passed in <paramref name="templateName"/>.
        /// </param>
        public StronglyTypedIdDefaultsAttribute(string templateName)
        {
        }

        /// <summary>
        /// Set the default template to use for strongly typed IDs
        /// </summary>
        /// <param name="templateName">The name of the template to use to generate the ID.
        /// Templates must be added to the project using the format NAME.typedid,
        /// where NAME is the name of the template passed in <paramref name="templateName"/>.
        /// </param>
        public StronglyTypedIdDefaultsAttribute(string templateName, params string[] templateNames)
        {
        }
    }
}